In [2]:
import geopandas as gpd

In [5]:
# oam_foot = gpd.read_file('../oam_global_footprints.gpkg')
oam_foot

,oam_id,title,provider,acquired,gsd_cm,area_km2,center_lat,center_lon,country,tms_url,download,continent,pass_baseline,geometry
0,59e62b863d6412ef72209ae1,Carretera _ Puente Rio Chico,Santiago Pastor,2016-04-27,0.000,0.3991,-0.977484,-80.421768,,,https://oin-hotosm-temp.s3.amazonaws.com/573a1...,South America,0,"POLYGON ((-80.41892 -0.98033, -80.41892 -0.974..."
1,59e62b903d6412ef7220a022,Johnson Valley - Soggy Dry Lake Yardangs,Douglas John Ellison,2016-12-04,0.000,0.0681,34.427203,-116.595296,,,https://oin-hotosm-temp.s3.amazonaws.com/58e86...,North America,0,"POLYGON ((-116.59387 34.42603, -116.59387 34.4..."
2,59e62b903d6412ef7220a029,Johnson Valley Soggy Dry Lake Cracks,Douglas J Ellison,2016-12-04,0.000,0.1360,34.452297,-116.687835,,,https://oin-hotosm-temp.s3.amazonaws.com/58e86...,North America,0,"POLYGON ((-116.68582 34.45064, -116.68582 34.4..."
3,59e62b863d6412ef72209b3d,Tapias - Centro Poblado,UMH Unidad de Mapeo Humanitario,2016-10-01,0.000,0.3110,4.453490,-75.351012,,,https://oin-hotosm-temp.s3.amazonaws.com/57f03...,South America,0,"POLYGON ((-75.34849 4.45098, -75.34849 4.456, ..."
4,59e62b903d6412ef7220a02f,Pisgah Crater Cinder Cone,Douglas J Ellison,2016-05-01,0.000,0.8177,34.746739,-116.375186,,,https://oin-hotosm-temp.s3.amazonaws.com/58e87...,North America,0,"POLYGON ((-116.37023 34.74267, -116.37023 34.7..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10671,5b948d519c75ae0006571e60,Minsk,Darafei Praliaskouski,2018-09-07,220.513,667.0820,54.060370,27.737836,,,https://oin-hotosm-temp.s3.amazonaws.com/5b948...,Europe,0,"POLYGON ((27.93606 53.94403, 27.93606 54.17671..."
10672,5b948d1b9c75ae0006571e54,Minsk,Darafei Praliaskouski,2018-09-07,368.473,70.9613,53.950881,27.527461,,,https://oin-hotosm-temp.s3.amazonaws.com/5b948...,Europe,0,"POLYGON ((27.59194 53.91294, 27.59194 53.98883..."
10673,67ce52e208baa2fabc550303,er,RGB,2024-12-09,500.228,45.2267,14.987122,43.011757,,,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Africa,0,"POLYGON ((43.04312 14.95683, 43.04312 15.01742..."
10674,65afcfcf71b11e0001cea8fe,DTM Pesisir Poncosari,Kel PRGG,2023-09-19,517.616,4.0526,-7.988015,110.220898,,,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Oceania,0,"POLYGON ((110.23005 -7.99708, 110.23005 -7.978..."
10675,6911b9855fa55e30b5187c11,TRAK,Robert Howe,2025-11-10,1098.218,162.5030,-0.036599,-79.433940,,,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,South America,0,"POLYGON ((-79.37652 -0.09402, -79.37652 0.0208..."

In [1]:
import json
import math
import requests
from pathlib import Path
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point, LineString, shape, mapping

# ─── CONFIGURATION ───
MAPILLARY_TOKEN = "MLY|6932788170076425|9c9b48dbda876b0e3a455489be41d7f1"
TARGET_OAM_ID = "59e62b943d6412ef7220a29d"  # Replace with any OAM ID to test
BUFFER_RADIUS_M = 35.0                      # Max distance from street to building
FOV_TOLERANCE_DEG = 45.0                    # Camera must face within ±45° of building centroid

GEOJSON_DIR = Path("../osm_geojson_results")
OAM_CACHE_FILE = Path("../cache_fast_bbox/oam/all_uav.json")

def calculate_bearing(p1, p2):
    """Calculates geographic bearing from Point 1 to Point 2."""
    dx = p2.x - p1.x
    dy = p2.y - p1.y
    angle = math.degrees(math.atan2(dx, dy))
    return (angle + 360) % 360

def angular_difference(angle1, angle2):
    """Calculates the absolute shortest distance between two angles."""
    diff = abs(angle1 - angle2) % 360
    return diff if diff <= 180 else 360 - diff

def get_scene_bbox(scene_id):
    """Retrieves the bounding box for the target scene from the OAM cache."""
    if not OAM_CACHE_FILE.exists():
        raise FileNotFoundError(f"Cannot find {OAM_CACHE_FILE}")
    
    data = json.loads(OAM_CACHE_FILE.read_text())
    for rec in data:
        if rec.get("_id") == scene_id:
            return rec.get("bbox")
    raise ValueError(f"Scene ID {scene_id} not found in catalog.")

def fetch_mapillary_data(bbox):
    """Fetches Mapillary points and sequence IDs inside the bbox."""
    min_lon, min_lat, max_lon, max_lat = bbox
    url = "https://graph.mapillary.com/images"
    
    response = requests.get(url, params={
        "access_token": MAPILLARY_TOKEN,
        "fields": "id,geometry,compass_angle,sequence_id",
        "bbox": f"{min_lon},{min_lat},{max_lon},{max_lat}",
        "limit": 1000
    })
    
    data = response.json().get("data", [])
    if not data:
        return gpd.GeoDataFrame()
        
    features = []
    for item in data:
        coords = item["geometry"]["coordinates"]
        features.append({
            "geometry": Point(coords[0], coords[1]),
            "mapillary_id": item["id"],
            "compass_angle": item.get("compass_angle", 0.0),
            "sequence_id": item.get("sequence_id", "")
        })
        
    return gpd.GeoDataFrame(features, crs="EPSG:4326")

def load_osm_buildings(scene_id):
    """Loads previously downloaded OSM buildings for the scene."""
    filepath = GEOJSON_DIR / f"{scene_id}_osm_buildings.geojson"
    if not filepath.exists():
        raise FileNotFoundError(f"OSM geometry not found: {filepath}. Run downloader first.")
    
    gdf = gpd.read_file(filepath)
    # Filter out the bounding box polygon if present
    gdf = gdf[gdf["source"] != "search_bounding_box"]
    return gdf

# ─── MAIN PROCESSING ───
print(f"🎯 Target Scene: {TARGET_OAM_ID}")

🎯 Target Scene: 59e62b943d6412ef7220a29d

In [2]:

# 1. Load Geometries
bbox = get_scene_bbox(TARGET_OAM_ID)
buildings_gdf = load_osm_buildings(TARGET_OAM_ID)
mapillary_gdf = fetch_mapillary_data(bbox)

print(f"🏢 Loaded {len(buildings_gdf)} buildings from local storage.")
print(f"📷 Fetched {len(mapillary_gdf)} Mapillary points.")

if mapillary_gdf.empty or buildings_gdf.empty:
    print("Cannot perform Line of Sight calculation: missing buildings or images.")
else:
    # 2. Convert to metric CRS (Web Mercator) for accurate distance buffers
    bldgs_m = buildings_gdf.to_crs(epsg=3857)
    maps_m = mapillary_gdf.to_crs(epsg=3857)

    # 3. Create spatial buffers around Mapillary points (simulating search radius)
    maps_buffered = maps_m.copy()
    maps_buffered["geometry"] = maps_buffered.geometry.buffer(BUFFER_RADIUS_M)

    # 4. Spatial Join: Find buildings intersecting the camera buffers
    joined = gpd.sjoin(bldgs_m, maps_buffered, how="inner", predicate="intersects")
    
    valid_links = []
    sight_lines = []

    # 5. Line of Sight (LOS) and Bearing Math
    for idx, row in joined.iterrows():
        bldg_geom = row["geometry"]  # Metric building geometry
        bldg_centroid = bldg_geom.centroid
        
        # Get original camera point in metric CRS
        cam_point = maps_m.loc[row["index_right"]].geometry
        
        # Calculate actual bearing from camera to building centroid
        bearing_to_bldg = calculate_bearing(cam_point, bldg_centroid)
        cam_compass = row["compass_angle"]
        
        # Calculate if camera is pointing at the building
        angle_diff = angular_difference(cam_compass, bearing_to_bldg)
        
        if angle_diff <= FOV_TOLERANCE_DEG:
            # Transform line back to WGS84 (EPSG:4326) for GeoJSON output
            bldg_wgs84 = buildings_gdf.loc[idx].geometry.centroid
            cam_wgs84 = mapillary_gdf.loc[row["index_right"]].geometry
            
            valid_links.append({
                "osm_id": row.get("osm_id", "unknown"),
                "mapillary_id": row["mapillary_id"],
                "distance_m": round(cam_point.distance(bldg_centroid), 1),
                "angle_diff": round(angle_diff, 1)
            })
            
            # Create a LineString ray representing the Line of Sight
            sight_lines.append({
                "type": "Feature",
                "properties": {
                    "source": "line_of_sight",
                    "osm_id": row.get("osm_id", "unknown"),
                    "mapillary_id": row["mapillary_id"]
                },
                "geometry": mapping(LineString([cam_wgs84, bldg_wgs84]))
            })

    print(f"✅ Found {len(valid_links)} valid Camera-to-Building links (within {BUFFER_RADIUS_M}m & ±{FOV_TOLERANCE_DEG}° FOV).")
    
    # 6. Generate Sequence Lines (connecting Mapillary paths)
    seq_lines = []
    for seq_id, group in mapillary_gdf.groupby("sequence_id"):
        if len(group) > 1:
            coords = [mapping(geom)["coordinates"] for geom in group.geometry]
            seq_lines.append({
                "type": "Feature",
                "properties": {"source": "mapillary_sequence", "sequence_id": seq_id},
                "geometry": {"type": "LineString", "coordinates": coords}
            })

    # 7. Compile Final GeoJSON for QGIS Inspection
    final_features = []
    
    # Add Buildings
    for _, row in buildings_gdf.iterrows():
        final_features.append({
            "type": "Feature",
            "properties": {"source": "osm_building", "osm_id": row.get("osm_id", "")},
            "geometry": mapping(row["geometry"])
        })
        
    # Add Cameras
    for _, row in mapillary_gdf.iterrows():
        final_features.append({
            "type": "Feature",
            "properties": {
                "source": "mapillary_camera", 
                "mapillary_id": row["mapillary_id"],
                "compass_angle": row["compass_angle"]
            },
            "geometry": mapping(row["geometry"])
        })

    # Add Sight Lines and Sequence Lines
    final_features.extend(sight_lines)
    final_features.extend(seq_lines)

    output_file = f"{TARGET_OAM_ID}_debug_los_filter.geojson"
    with open(output_file, "w") as f:
        json.dump({"type": "FeatureCollection", "features": final_features}, f, indent=2)

    print(f"💾 Exported visual debugging layer to: {output_file}")
    print(f"👉 Drag {output_file} into QGIS to verify the Field of View filtering.")

🏢 Loaded 98 buildings from local storage.
📷 Fetched 580 Mapillary points.
✅ Found 215 valid Camera-to-Building links (within 35.0m & ±45.0° FOV).
💾 Exported visual debugging layer to: 59e62b943d6412ef7220a29d_debug_los_filter.geojson
👉 Drag 59e62b943d6412ef7220a29d_debug_los_filter.geojson into QGIS to verify the Field of View filtering.

In [12]:
import json
import math
import requests
from pathlib import Path
import geopandas as gpd
import pandas as pd
import numpy as np
from shapely.geometry import Point, LineString, mapping

# ─── CONFIGURATION ───
MAPILLARY_TOKEN = "MLY|6932788170076425|9c9b48dbda876b0e3a455489be41d7f1"
TARGET_OAM_ID = "676020507264d60001bd98ab"  

ROAD_BUFFER_METERS = 20.0
NEARBY_DISTANCE_METERS = 20.0  # Distance from camera to POLYGON EDGE
FOV_TOLERANCE_DEG = 50.0

GEOJSON_DIR = Path("../osm_geojson_results")
OAM_CACHE_FILE = Path("../cache_fast_bbox/oam/all_uav.json")

def get_scene_bbox(scene_id):
    data = json.loads(OAM_CACHE_FILE.read_text())
    for rec in data:
        if rec.get("_id") == scene_id:
            return rec.get("bbox")
    raise ValueError(f"Scene ID {scene_id} not found in catalog cache.")

def fetch_mapillary(bbox):
    min_lon, min_lat, max_lon, max_lat = bbox
    r = requests.get("https://graph.mapillary.com/images", params={
        "access_token": MAPILLARY_TOKEN,
        "fields": "id,geometry,compass_angle,sequence_id,is_pano",
        "bbox": f"{min_lon},{min_lat},{max_lon},{max_lat}",
        "limit": 2000
    }, timeout=30)
    data = r.json().get("data", [])
    if not data: return gpd.GeoDataFrame()
    
    features = []
    for d in data:
        # FILTER: Skip panoramic images entirely
        if d.get("is_pano") == True:
            continue
            
        features.append({
            "geometry": Point(d["geometry"]["coordinates"]), 
            "mapillary_id": d["id"], 
            "compass_angle": d.get("compass_angle", 0.0), 
            "sequence_id": d.get("sequence_id", "")
        })
    return gpd.GeoDataFrame(features, crs="EPSG:4326")

def calculate_bearing(p1, p2):
    angle = math.degrees(math.atan2(p2.x - p1.x, p2.y - p1.y))
    return (angle + 360) % 360

# ─── EXECUTION ───
print(f"🎯 Testing Polygon-Edge Distance Scoring on Scene: {TARGET_OAM_ID}")

bbox = get_scene_bbox(TARGET_OAM_ID)
bldgs_wgs84 = gpd.read_file(GEOJSON_DIR / f"{TARGET_OAM_ID}_osm_buildings.geojson")
bldgs_wgs84 = bldgs_wgs84[bldgs_wgs84["source"] != "search_bounding_box"].reset_index(drop=True)

if "osm_id" not in bldgs_wgs84.columns:
    bldgs_wgs84["osm_id"] = bldgs_wgs84.index.astype(str)

maps_wgs84 = fetch_mapillary(bbox)

total_buildings = len(bldgs_wgs84)
total_svi = len(maps_wgs84)

print(f"🏢 Total OSM Buildings: {total_buildings}")
print(f"📷 Total Non-Panoramic Mapillary Points: {total_svi}")

if total_buildings == 0 or total_svi == 0:
    print("Zero buildings or valid SVI points. Score is 0.")
else:
    utm_crs = bldgs_wgs84.estimate_utm_crs()
    bldgs_utm = bldgs_wgs84.to_crs(utm_crs)
    maps_utm = maps_wgs84.to_crs(utm_crs)

    # 1. Buffer Mapillary Paths
    seq_lines = []
    for _, group in maps_utm.groupby("sequence_id"):
        if len(group) > 1:
            seq_lines.append(LineString(group.geometry.tolist()))
        else:
            seq_lines.append(group.geometry.iloc[0])
            
    paths_buffered = gpd.GeoDataFrame(geometry=seq_lines, crs=utm_crs).buffer(ROAD_BUFFER_METERS)

    # 2. Filter Buildings on Path
    bldgs_on_path = gpd.sjoin(bldgs_utm, gpd.GeoDataFrame(geometry=paths_buffered), how="inner", predicate="intersects")
    bldgs_on_path = bldgs_on_path[~bldgs_on_path.index.duplicated(keep='first')]
    print(f"✂️ Buildings within {ROAD_BUFFER_METERS}m of driven path: {len(bldgs_on_path)}")

    # 3. True Edge-Distance & LoS Check
    valid_pairs = 0
    all_buildings_sindex = bldgs_utm.sindex
    debug_features = []

    for bldg_idx, bldg in bldgs_on_path.iterrows():
        target_pos_idx = bldgs_utm.index.get_loc(bldg_idx)
        
        # Calculate distance from ALL Mapillary points to this building's POLYGON EDGE
        distances = maps_utm.geometry.distance(bldg.geometry)
        min_dist = distances.min()
        
        # Apply strict 20m cutoff to the building facade/edge
        if min_dist > NEARBY_DISTANCE_METERS:
            continue
            
        # Get the single closest camera
        cam_idx = distances.idxmin()
        cam = maps_utm.loc[cam_idx]
        centroid = bldg.geometry.centroid
        
        # Bearing and FOV (Still aimed at centroid to ensure looking at the main building mass)
        bearing = calculate_bearing(cam.geometry, centroid)
        angle_diff = abs(cam["compass_angle"] - bearing) % 360
        angle_diff = angle_diff if angle_diff <= 180 else 360 - angle_diff
        
        cam_wgs84 = maps_wgs84.loc[cam_idx].geometry
        bldg_wgs84_cent = bldgs_wgs84.iloc[target_pos_idx].geometry.centroid
        
        if angle_diff <= FOV_TOLERANCE_DEG:
            # Occlusion Check
            los_line = LineString([cam.geometry, centroid])
            possible_blockers_pos_idx = list(all_buildings_sindex.intersection(los_line.bounds))
            
            is_occluded = False
            for blocker_pos in possible_blockers_pos_idx:
                if blocker_pos != target_pos_idx: # Safely ignore the target building itself
                    blocker_geom = bldgs_utm.iloc[blocker_pos].geometry
                    if los_line.intersects(blocker_geom):
                        is_occluded = True
                        break
            
            if not is_occluded:
                valid_pairs += 1
                status = "valid_los"
            else:
                status = "occluded"
        else:
            status = "bad_angle"

        # Add to debug visualization
        debug_features.append({
            "type": "Feature",
            "properties": {"status": status, "edge_distance_m": round(min_dist, 1), "angle_diff": round(angle_diff, 1)},
            "geometry": mapping(LineString([cam_wgs84, bldg_wgs84_cent]))
        })

    print(f"✅ Valid Non-Occluded Matches (Score): {valid_pairs}")

    # Export Debug GeoJSON
    for idx, row in bldgs_wgs84.loc[bldgs_on_path.index].iterrows():
        debug_features.append({"type": "Feature", "properties": {"source": "building_on_path", "osm_id": row.get("osm_id", "")}, "geometry": mapping(row["geometry"])})
    for _, row in maps_wgs84.iterrows():
        debug_features.append({"type": "Feature", "properties": {"source": "mapillary", "angle": row["compass_angle"]}, "geometry": mapping(row["geometry"])})

    out_file = f"{TARGET_OAM_ID}_enrichment_debug.geojson"
    with open(out_file, "w") as f:
        json.dump({"type": "FeatureCollection", "features": debug_features}, f, indent=2)
    print(f"💾 Saved debug GeoJSON to {out_file}")

🎯 Testing Polygon-Edge Distance Scoring on Scene: 676020507264d60001bd98ab
🏢 Total OSM Buildings: 181
📷 Total Non-Panoramic Mapillary Points: 836
✂️ Buildings within 20.0m of driven path: 97
✅ Valid Non-Occluded Matches (Score): 3
💾 Saved debug GeoJSON to 676020507264d60001bd98ab_enrichment_debug.geojson

In [15]:
scene  = pd.read_csv("../scene_enrichment_scores.csv")
scene['valid_los_matches'].sum()

np.int64(3452)

In [31]:
import pandas as pd
import geopandas as gpd
import json
from shapely.geometry import Point
from pathlib import Path

# Paths
SCORES_CSV = Path("../scene_enrichment_scores.csv")
OAM_CACHE_FILE = Path("../cache_fast_bbox/oam/all_uav.json")

print("Loading data...")
# df = pd.read_csv(SCORES_CSV)

# # 1. Get the center coordinates for all scenes from the local cache
# with open(OAM_CACHE_FILE, "r") as f:
#     catalog = json.load(f)

# points = {}
# for rec in catalog:
#     if "_id" in rec and "bbox" in rec:
#         bbox = rec["bbox"]
#         # bbox is [min_lon, min_lat, max_lon, max_lat]
#         center_lon = (bbox[0] + bbox[2]) / 2.0
#         center_lat = (bbox[1] + bbox[3]) / 2.0
#         points[str(rec["_id"])] = Point(center_lon, center_lat)

# # 2. Map the geometries to our dataframe
# df['geometry'] = df['scene_id'].astype(str).map(points)

# # Drop any rows where we couldn't find a bounding box, just in case
# df = df.dropna(subset=['geometry'])

# # Convert to a GeoDataFrame
# gdf = gpd.GeoDataFrame(df, geometry='geometry', crs="EPSG:4326")

# # 3. Load GeoPandas' built-in World Map
# print("Performing spatial join with global map...")
# world = gpd.read_file('../NE/ne_110m_admin_0_map_units.shp')

# 4. Perform Spatial Join (Find which country polygon intersects our center point)
gdf_mapped = gpd.sjoin(gdf, world[['geometry', 'REGION_UN','SUBREGION','ADMIN']], how="left", predicate="intersects")

# Rename 'name' to 'country' for clarity
gdf_mapped = gdf_mapped.rename(columns={'name': 'country'})

# 5. Clean up and save back to CSV
# Drop the spatial join artifact columns so it remains a clean, standard CSV
final_df = pd.DataFrame(gdf_mapped.drop(columns=['geometry', 'index_right']))

final_df.to_csv(SCORES_CSV, index=False)

print(f"✅ Successfully added 'country' and 'continent' to {SCORES_CSV.name}!")
print("\nPreview of the enriched dataset:")
# print(final_df[['scene_id', 'valid_los_matches', 'country', 'continent']].head(10))

Loading data...
✅ Successfully added 'country' and 'continent' to scene_enrichment_scores.csv!

Preview of the enriched dataset:

In [73]:
final_nonzero = final_df[final_df['valid_los_matches'] != 0]
final_nonzero

,scene_id,title,gsd_cm,area_km2,mapillary_ok,osm_ok,building_count,pass,reason,elapsed_s,total_buildings,total_svi_points,buildings_on_path,valid_los_matches,REGION_UN,SUBREGION,ADMIN
0,68b709ea5288a43ff3e919db,Freetown_New_England_and_Kingtom_COG,4.000,17.4460,True,True,24,True,pass,0.00,69292,810,21030,277,NaN,NaN,NaN
1,688ca9be5c13f65e3cc03bcc,Kroo Bay KYC - Full,4.988,1.4478,True,True,2,True,pass,0.01,8898,876,8042,240,NaN,NaN,NaN
2,686f12ef0af31ae7caac8152,Kroo_Bay_Disability_Analysis,5.000,1.4563,True,True,2,True,pass,0.01,8962,872,6529,239,NaN,NaN,NaN
3,61195da8ac1a340005a1cd6c,"вул. Данила Нечая, Вінниця",4.158,5.3168,True,False,0,False,no_residential_osm,0.01,3832,1359,2503,186,Europe,Eastern Europe,Ukraine
4,686eb4010af31ae7caac165f,Kolleh_Town_Disability_Analysis,5.000,1.4661,True,False,0,False,no_residential_osm,0.01,5876,651,5262,185,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,69bb03dea2cd858f4ba47ee3,Mathew 2016 -Jérémie,5.746,8.3752,True,False,0,False,no_residential_osm,0.00,12989,1,1,1,NaN,NaN,NaN
145,5e314797fbfe8c00073c70e0,2020-01-10 台中梧棲龍井安良排水治理工程(2-4K)提案階段 (Anlian Ch...,3.029,3.3585,True,False,0,False,no_residential_osm,0.01,6,1173,6,1,Asia,Eastern Asia,Taiwan
146,6420eb3b1a8878000512122b,Rangitopuni_230324_Ortho_0050m,5.000,9.0059,True,False,0,False,no_residential_osm,0.00,301,196,63,1,Oceania,Australia and New Zealand,New Zealand
147,5ec3c8fdaff5010005865c51,"СПб, Невский район, ул. Седова, Epoch 2010.0",5.422,2.3030,True,False,0,False,no_residential_osm,0.00,571,15,27,1,Europe,Eastern Europe,Russia
148,65d6f40d5324bf00019a0e6a,Estrada Rubim MG,5.461,1.1724,True,False,0,False,no_residential_osm,0.00,2,817,2,1,Americas,South America,Brazil

In [81]:
print(['valid_los_matches'].sum())

3452

In [ ]:
all_uav = pd.read_json('../cache_fast_bbox/oam/all_uav.json')

,_id,uuid,__v,title,projection,bbox,footprint,gsd,file_size,acquisition_start,acquisition_end,platform,provider,contact,properties,uploaded_at,meta_uri,geojson,user
0,59e62b863d6412ef72209ae1,https://oin-hotosm-temp.s3.amazonaws.com/573a1...,0,Carretera _ Puente Rio Chico,"GEOGCS[""WGS 84"",DATUM[""WGS_1984"",SPHEROID[""WGS...","[-80.4248105, -0.9801461999990001, -80.4187253...","POLYGON((-80.4248105 -0.9748216999999999,-80.4...",1.857046e-07,47649982,2016-04-27T05:00:00.000Z,2016-04-28T17:00:03.000Z,uav,Santiago Pastor,"fruizc,francisco.ruiz@engeotec.net",{'wmts': 'http://tiles.openaerialmap.org/573a1...,2016-05-16 00:00:00+00:00,https://oin-hotosm-temp.s3.amazonaws.com/573a1...,"{'bbox': [-80.4248105, -0.9801461999990001, -8...",NaN
1,59e62b903d6412ef7220a022,https://oin-hotosm-temp.s3.amazonaws.com/58e86...,0,Johnson Valley - Soggy Dry Lake Yardangs,"GEOGCS[""WGS 84"",DATUM[""WGS_1984"",SPHEROID[""WGS...","[-116.59716988178567, 34.42630988440853, -116....",POLYGON((-116.59716988178567 34.42809659794853...,1.989375e-07,32572534,2016-12-04T20:00:00.000Z,2016-12-04T21:00:00.000Z,uav,Douglas John Ellison,"Doug Ellison,douglas.j.ellison@gmail.com","{'license': 'CC-BY 4.0', 'sensor': 'DJI Phanto...",2017-04-08 04:57:38.054000+00:00,https://oin-hotosm-temp.s3.amazonaws.com/58e86...,"{'bbox': [-116.59716988178567, 34.426309884408...",NaN
2,59e62b903d6412ef7220a029,https://oin-hotosm-temp.s3.amazonaws.com/58e86...,0,Johnson Valley Soggy Dry Lake Cracks,"GEOGCS[""WGS 84"",DATUM[""WGS_1984"",SPHEROID[""WGS...","[-116.68984993967797, 34.4506361486674, -116.6...",POLYGON((-116.68984993967797 34.45395858684593...,1.989696e-07,38470684,2016-12-04T23:00:00.000Z,2016-12-05T00:00:00.000Z,uav,Douglas J Ellison,"Doug Ellison,douglas.j.ellison@gmail.com","{'license': 'CC-BY 4.0', 'sensor': 'DJI Phanto...",2017-04-08 04:59:05.713000+00:00,https://oin-hotosm-temp.s3.amazonaws.com/58e86...,"{'bbox': [-116.68984993967797, 34.450636148667...",NaN
3,59e62b863d6412ef72209b3d,https://oin-hotosm-temp.s3.amazonaws.com/57f03...,0,Tapias - Centro Poblado,"GEOGCS[""WGS 84"",DATUM[""WGS_1984"",SPHEROID[""WGS...","[-75.35279172145262, 4.449932472396174, -75.34...",POLYGON((-75.35279172145262 4.4570479457401735...,2.928145e-07,33151045,2016-10-01T05:00:00.000Z,2016-10-01T22:10:07.345Z,uav,UMH Unidad de Mapeo Humanitario,"Humano,fredyrivera@gmail.com",{'wmts': 'http://tiles.openaerialmap.org/57f03...,2016-10-01 00:00:00+00:00,https://oin-hotosm-temp.s3.amazonaws.com/57f03...,"{'bbox': [-75.35279172145262, 4.44993247239617...",NaN
4,59e62b903d6412ef7220a02f,https://oin-hotosm-temp.s3.amazonaws.com/58e87...,0,Pisgah Crater Cinder Cone,"GEOGCS[""WGS 84"",DATUM[""WGS_1984"",SPHEROID[""WGS...","[-116.38018350872743, 34.74269850450097, -116....",POLYGON((-116.38018350872743 34.75077985936303...,2.990238e-07,53554806,2016-05-01T07:00:00.000Z,2016-05-01T07:00:00.000Z,uav,Douglas J Ellison,"Doug Ellison,douglas.j.ellison@gmail.com","{'license': 'CC-BY 4.0', 'sensor': 'Phantom 3 ...",2017-04-08 05:11:08.440000+00:00,https://oin-hotosm-temp.s3.amazonaws.com/58e87...,"{'bbox': [-116.38018350872743, 34.742698504500...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11130,5b948d519c75ae0006571e60,https://oin-hotosm-temp.s3.amazonaws.com/5b948...,0,Minsk,"PROJCS[""unnamed"",GEOGCS[""unnamed ellipse"",DATU...","[27.561734, 53.929415, 27.913937, 54.191325]","POLYGON ((27.561734 53.929415, 27.913937 53.92...",2.205126e+00,7050553,2018-09-07T21:00:00.000Z,2018-09-07T22:00:00.000Z,uav,Darafei Praliaskouski,"Darafei Praliaskouski,komzpa@gmail.com",{'wmts': 'https://tiles.openaerialmap.org/5b94...,2018-09-09 03:02:41.934000+00:00,https://oin-hotosm-temp.s3.amazonaws.com/5b948...,"{'bbox': [27.561734, 53.929415, 27.913937, 54....","{'_id': '5a02e4c331eff4000c380594', 'name': 'D..."
11131,5b948d1b9c75ae0006571e54,https://oin-hotosm-temp.s3.amazonaws.com/5b948...,0,Minsk,"PROJCS[""unnamed"",GEOGCS[""unnamed ellipse"",DATU...","[27.451793, 53.918546, 27.603129, 53.983216]","POLYGON ((27.451793 53.918546, 27.603129 53.91...",3.684731e+00,965614,2018-09-07T21:00:00.000Z,2018-09-07T22:00:00.000Z,uav,Darafei Praliaskouski,"Darafei Praliaskouski,komzpa@gmail.com",{'wmts': 'https://tiles.openaerialmap.org/5b94...,2018-09-09 03:01:47.997000+00:00,https://oin-hotosm-temp.s3.amazonaws.com/5b948...,"{'bbox': [27.451793, 53.918546, 27.603129, 53....","{'_id': '5a02e4c331eff4000c380594', 'name': 'D..."
11132,67ce52e208baa2fabc550303,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,0,er,"\nGEOGCRS[""WGS 84"",\n ENSEMBLE[""World Geode...","[42.966542, 14.966111, 43.056972, 15.008132]","POLYGON ((42.966542 14.966111, 43.056972 14.96...",5.002285e+00,212968,2024-12-09T21:00:00.000Z,2024-12-09T22:00:00.000Z,uav,RGB,"AboAhmad Almohtachm,almohtachm2@gmail.com","{'license': 'CC-BY 4.0', 'sensor': 'lid-20c', ...",2025-03-10 02:48:02.931000+00:00,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,"{'type': 'MultiPolygon', 'coordinates': [[[[42...","{'_id': '67ce4ac808baa2fabc54fe12', 'name': 'A..."
11133,65afcfcf71b11e0001cea8fe,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,0,DTM Pesisir Poncosari,"\nPROJCRS[""WGS 84 / UTM zone 49S"",\n BASEGE...","[110.206774, -7.993894, 110.235022, -7.982136]","POLYGON ((110.206774 -7.993894, 110.235022 -7....",5.176156e+00,61274,2023-09-19T17:00:00.000Z,2023-09-20T10:51:55.416Z,uav,Kel PRGG,"Spatiallity,spatiallity@gmail.com",{'tilejson': 'https://tiles.openaerialmap.org/...,2024-01-23 14:40:15.317000+00:00,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,"{'bbox': [110.206774, -7.993894, 110.235022, -...","{'_id': '65007062649d390001c4758d', 'name': 'S..."
11134,6911b9855fa55e30b5187c11,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,0,TRAK,"\nPROJCRS[""WGS 84 / UTM zone 18N"",\n BASEGE...","[-79.514332, -0.077614, -79.353548, 0.004416]","POLYGON ((-79.514332 -0.077614, -79.353548 -0....",1.098218e+01,220080,2025-11-10T05:00:00.000Z,2025-11-10T09:24:11.174Z,uav,Robert Howe,"Bobby Howe,bh7406@bard.edu","{'license': 'CC-BY 4.0', 'sensor': 'RBG', 'url...",2025-11-10 10:08:05.348000+00:00,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...","{'_id': '68de10bf41031d3004ec4fd2', 'name': 'B..."

In [142]:
all_uav['geometry'] = all_uav['geojson'].apply(shape)
all_uav = gpd.GeoDataFrame(
    all_uav,
    geometry='geometry',
    crs='EPSG:4326'
)
# Save as GeoPackage
out = '../cache_fast_bbox/oam/all_uav.gpkg'

all_uav.to_file(
    out,
    driver='GPKG'
)

In [162]:
scene_enrichment_scores = pd.read_csv('../scene_enrichment_scores.csv')
# Match all_uav._id -> scene_enrichment_scores.scene_id
matched = all_uav.merge(
    scene_enrichment_scores,
    left_on='_id',
    right_on='scene_id',
    how='inner',
    suffixes=('_uav', '_los')
)

# Convert GeoJSON dict to Shapely geometry
matched['geometry'] = matched['geojson'].apply(shape)

# Create GeoDataFrame
matched_gdf = gpd.GeoDataFrame(
    matched,
    geometry='geometry',
    crs='EPSG:4326'
)
matched_gdf.drop(columns=['__v', 'scene_id','mapillary_ok', 'osm_ok', 'building_count', 'pass','reason', 'elapsed_s','title_los'], inplace=True)

matched_gdf.rename(columns={'title_uav': 'title'}, inplace=True)
matched_gdf
# # Save as GeoPackage
# out = '../cache_fast_bbox/oam/final_nonzero_uav2.gpkg'

# matched_gdf.to_file(
#     out,
#     layer='uav_matches',
#     driver='GPKG'
# )

# print(f"Saved {len(matched_gdf)} records to {out}")

,_id,uuid,title,projection,bbox,footprint,gsd,file_size,acquisition_start,acquisition_end,...,meta_uri,geojson,user,geometry,gsd_cm,area_km2,total_buildings,total_svi_points,buildings_on_path,valid_los_matches
0,6a2d426391730de10f6bb33e,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,The Original City Center of Jeju City in Korea,"\nPROJCRS[""KGD2002 / Central Belt 2010"",\n ...","[126.516331, 33.506763, 126.533065, 33.518614]","POLYGON ((126.516331 33.506763, 126.533065 33....",0.010000,3231859293,2023-09-30T15:00:00.000Z,2023-10-31T14:59:00.000Z,...,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,"{'type': 'MultiPolygon', 'coordinates': [[[[12...","{'_id': '6a2a3dc4882f78eab98373e0', 'name': 'S...","MULTIPOLYGON (((126.51633 33.51855, 126.5164 3...",1.000,2.0372,4908,471,2954,40
1,652a6a10db601900014daad6,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,M2_22Feb22_35_transparent_mosaic_group1,"\nPROJCRS[""WGS 84 / UTM zone 46N"",\n BASEGE...","[90.360887, 23.837113, 90.3739, 23.846721]","POLYGON ((90.360887 23.837113, 90.3739 23.8371...",0.012120,1032502531,2023-10-13T18:00:00.000Z,2023-10-14T04:10:40.342Z,...,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,"{'bbox': [90.360887, 23.837113, 90.3739, 23.84...","{'_id': '64a3a9e664adbc00012e07f9', 'name': 'd...","MULTIPOLYGON (((90.36089 23.8465, 90.36108 23....",1.212,1.4090,1137,1877,889,30
2,6529bc2ddb601900014daac4,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,sagufta_03Feb22_M1_transparent_mosaic_group1_33,"\nPROJCRS[""WGS 84 / UTM zone 46N"",\n BASEGE...","[90.374979, 23.829543, 90.384209, 23.842295]","POLYGON ((90.374979 23.829543, 90.384209 23.82...",0.012260,987138849,2023-10-12T18:00:00.000Z,2023-10-12T22:38:10.456Z,...,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,"{'bbox': [90.374979, 23.829543, 90.384209, 23....","{'_id': '64a3a9e664adbc00012e07f9', 'name': 'd...","MULTIPOLYGON (((90.38021 23.84053, 90.38021 23...",1.226,1.3265,1110,1665,558,11
3,5a9f2f195a9ef7cb5da703e4,https://oin-hotosm-temp.s3.amazonaws.com/5a9f2...,TC-Gita-2018_UAV4R_Flight8,"GEOGCS[""WGS 84"",DATUM[""WGS_1984"",SPHEROID[""WGS...","[-175.2531898897765, -21.204050291607338, -175...","POLYGON ((-175.253189889777 -21.2040502916073,...",0.014327,891845475,2018-02-24T11:00:00.000Z,2018-02-24T11:00:00.000Z,...,https://oin-hotosm-temp.s3.amazonaws.com/5a9f2...,"{'bbox': [-175.2531898897765, -21.204050291607...","{'_id': '5a0d77ff31eff4000c3805da', 'name': 'C...","POLYGON ((-175.25319 -21.20405, -175.22681 -21...",1.433,29.7513,3979,66,351,18
4,5efb1ead8fec2a0005992d10,https://oin-hotosm-temp.s3.amazonaws.com/5efb1...,Ile de Saint Louis,"PROJCS[""WGS 84 / UTM zone 28N"",GEOGCS[""WGS 84""...","[-16.507769, 16.018057, -16.500973, 16.039249]","POLYGON ((-16.507769 16.018057, -16.500973 16....",0.014407,754731543,2019-08-17T22:00:00.000Z,2019-08-17T23:00:00.000Z,...,https://oin-hotosm-temp.s3.amazonaws.com/5efb1...,"{'bbox': [-16.507769, 16.018057, -16.500973, 1...","{'_id': '5eec7f22d6806200078e07f7', 'name': 'L...","MULTIPOLYGON (((-16.50777 16.0392, -16.50761 1...",1.441,1.7055,2511,1782,2055,59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,60f45e8a42311e0006681a1d,https://oin-hotosm-temp.s3.amazonaws.com/60f45...,Kar'er 1,"PROJCS[""WGS 84 / UTM zone 35N"",GEOGCS[""WGS 84""...","[27.15347, 54.113759, 27.177924, 54.126002]","POLYGON ((27.15347 54.113759, 27.177924 54.113...",0.059693,117417305,2021-07-15T21:00:00.000Z,2021-07-15T22:00:00.000Z,...,https://oin-hotosm-temp.s3.amazonaws.com/60f45...,"{'bbox': [27.15347, 54.113759, 27.177924, 54.1...","{'_id': '5d4b128aff91220007fbc33c', 'name': 'А...","MULTIPOLYGON (((27.15352 54.126, 27.15347 54.1...",5.969,2.1620,111,1451,2,1
713,64b01515f1006f000147ae78,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Kalobeyei_Mission 6_Flight_02,"\nPROJCRS[""WGS 84 / UTM zone 36N"",\n BASEGE...","[34.731548, 3.735658, 34.75056, 3.749924]","POLYGON ((34.731548 3.735658, 34.75056 3.73565...",0.059908,49043703,2022-11-10T06:00:00.000Z,2022-11-10T09:00:00.000Z,...,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,"{'bbox': [34.731548, 3.735658, 34.75056, 3.749...","{'_id': '64b00099f1006f000147ae53', 'name': 'W...","MULTIPOLYGON (((34.73158 3.74992, 34.73155 3.7...",5.991,3.3346,633,727,581,2
714,5f133b8dbaa90f0006a0ab29,https://oin-hotosm-temp.s3.amazonaws.com/5f133...,Озеро Задорожное,"PROJCS[""WGS 84 / UTM zone 34N"",GEOGCS[""WGS 84""...","[23.911744, 49.547664, 23.924438, 49.557918]","POLYGON ((23.911744 49.547664, 23.924438 49.54...",0.059972,19559359,2020-07-11T06:15:00.000Z,2020-07-11T06:30:00.000Z,...,https://oin-hotosm-temp.s3.amazonaws.com/5f133...,"{'bbox': [23.911744, 49.547664, 23.924438, 49....","{'_id': '5e46a3ebae704f00063a4869', 'name': 'V...","MULTIPOLYGON (((23.91234 49.55792, 23.91174 49...",5.997,1.0404,224,60,1,0
715,65d3b7fed1f3d200015493e0,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Cooperativa HUAYÑA PASTO 4,"\nPROJCRS[""WGS 84 / UTM zone 19S"",\n BASEGE...","[-66.954823, -18.047041, -66.938041, -18.032018]","POLYGON ((-66.954823 -18.047041, -66.938041 -1...",0.060000,127566170,2024-02-07T14:00:00.000Z,2024-02-07T15:00:00.000Z,...,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,"{'bbox': [-66.954823, -18.047041, -66.938041, ...","{'_id': '5d3f0ef9db56bc0007420e16', 'name': 'R...","MULTIPOLYGON (((-66.95482 -18.0322, -66.95465 ...",6.000,2.9536,0,1324,0,0
716,65d3a70ed1f3d200015493c9,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Cooperativa HUAYÑA PASTO 2,"\nPROJCRS[""WGS 84 / UTM zone 19S"",\n BASEGE...","[-66.954131, -18.034791, -66.937832, -18.02191]","POLYGON ((-66.954131 -18.034791, -66.937832 -1...",0.060000,119262238,2024-02-07T14:00:00.000Z,2024-02-07T15:00:00.000Z,...,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,"{'bbox': [-66.954131, -18.034791, -66.937832, ...","{'_id': '5d3f0ef9db56bc0007420e16', 'name': 'R...","MULTIPOLYGON (((-66.95413 -18.02208, -66.95398...",6.000,2.4598,0,1903,0,0

In [163]:
matched_gdf["has_overlap"] = False

for i, geom in matched_gdf.geometry.items():
    others = matched_gdf.geometry.drop(index=i)
    matched_gdf.loc[i, "has_overlap"] = others.overlaps(geom).any()
matched_gdf

,_id,uuid,title,projection,bbox,footprint,gsd,file_size,acquisition_start,acquisition_end,...,geojson,user,geometry,gsd_cm,area_km2,total_buildings,total_svi_points,buildings_on_path,valid_los_matches,has_overlap
0,6a2d426391730de10f6bb33e,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,The Original City Center of Jeju City in Korea,"\nPROJCRS[""KGD2002 / Central Belt 2010"",\n ...","[126.516331, 33.506763, 126.533065, 33.518614]","POLYGON ((126.516331 33.506763, 126.533065 33....",0.010000,3231859293,2023-09-30T15:00:00.000Z,2023-10-31T14:59:00.000Z,...,"{'type': 'MultiPolygon', 'coordinates': [[[[12...","{'_id': '6a2a3dc4882f78eab98373e0', 'name': 'S...","MULTIPOLYGON (((126.51633 33.51855, 126.5164 3...",1.000,2.0372,4908,471,2954,40,False
1,652a6a10db601900014daad6,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,M2_22Feb22_35_transparent_mosaic_group1,"\nPROJCRS[""WGS 84 / UTM zone 46N"",\n BASEGE...","[90.360887, 23.837113, 90.3739, 23.846721]","POLYGON ((90.360887 23.837113, 90.3739 23.8371...",0.012120,1032502531,2023-10-13T18:00:00.000Z,2023-10-14T04:10:40.342Z,...,"{'bbox': [90.360887, 23.837113, 90.3739, 23.84...","{'_id': '64a3a9e664adbc00012e07f9', 'name': 'd...","MULTIPOLYGON (((90.36089 23.8465, 90.36108 23....",1.212,1.4090,1137,1877,889,30,False
2,6529bc2ddb601900014daac4,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,sagufta_03Feb22_M1_transparent_mosaic_group1_33,"\nPROJCRS[""WGS 84 / UTM zone 46N"",\n BASEGE...","[90.374979, 23.829543, 90.384209, 23.842295]","POLYGON ((90.374979 23.829543, 90.384209 23.82...",0.012260,987138849,2023-10-12T18:00:00.000Z,2023-10-12T22:38:10.456Z,...,"{'bbox': [90.374979, 23.829543, 90.384209, 23....","{'_id': '64a3a9e664adbc00012e07f9', 'name': 'd...","MULTIPOLYGON (((90.38021 23.84053, 90.38021 23...",1.226,1.3265,1110,1665,558,11,False
3,5a9f2f195a9ef7cb5da703e4,https://oin-hotosm-temp.s3.amazonaws.com/5a9f2...,TC-Gita-2018_UAV4R_Flight8,"GEOGCS[""WGS 84"",DATUM[""WGS_1984"",SPHEROID[""WGS...","[-175.2531898897765, -21.204050291607338, -175...","POLYGON ((-175.253189889777 -21.2040502916073,...",0.014327,891845475,2018-02-24T11:00:00.000Z,2018-02-24T11:00:00.000Z,...,"{'bbox': [-175.2531898897765, -21.204050291607...","{'_id': '5a0d77ff31eff4000c3805da', 'name': 'C...","POLYGON ((-175.25319 -21.20405, -175.22681 -21...",1.433,29.7513,3979,66,351,18,True
4,5efb1ead8fec2a0005992d10,https://oin-hotosm-temp.s3.amazonaws.com/5efb1...,Ile de Saint Louis,"PROJCS[""WGS 84 / UTM zone 28N"",GEOGCS[""WGS 84""...","[-16.507769, 16.018057, -16.500973, 16.039249]","POLYGON ((-16.507769 16.018057, -16.500973 16....",0.014407,754731543,2019-08-17T22:00:00.000Z,2019-08-17T23:00:00.000Z,...,"{'bbox': [-16.507769, 16.018057, -16.500973, 1...","{'_id': '5eec7f22d6806200078e07f7', 'name': 'L...","MULTIPOLYGON (((-16.50777 16.0392, -16.50761 1...",1.441,1.7055,2511,1782,2055,59,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,60f45e8a42311e0006681a1d,https://oin-hotosm-temp.s3.amazonaws.com/60f45...,Kar'er 1,"PROJCS[""WGS 84 / UTM zone 35N"",GEOGCS[""WGS 84""...","[27.15347, 54.113759, 27.177924, 54.126002]","POLYGON ((27.15347 54.113759, 27.177924 54.113...",0.059693,117417305,2021-07-15T21:00:00.000Z,2021-07-15T22:00:00.000Z,...,"{'bbox': [27.15347, 54.113759, 27.177924, 54.1...","{'_id': '5d4b128aff91220007fbc33c', 'name': 'А...","MULTIPOLYGON (((27.15352 54.126, 27.15347 54.1...",5.969,2.1620,111,1451,2,1,False
713,64b01515f1006f000147ae78,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Kalobeyei_Mission 6_Flight_02,"\nPROJCRS[""WGS 84 / UTM zone 36N"",\n BASEGE...","[34.731548, 3.735658, 34.75056, 3.749924]","POLYGON ((34.731548 3.735658, 34.75056 3.73565...",0.059908,49043703,2022-11-10T06:00:00.000Z,2022-11-10T09:00:00.000Z,...,"{'bbox': [34.731548, 3.735658, 34.75056, 3.749...","{'_id': '64b00099f1006f000147ae53', 'name': 'W...","MULTIPOLYGON (((34.73158 3.74992, 34.73155 3.7...",5.991,3.3346,633,727,581,2,True
714,5f133b8dbaa90f0006a0ab29,https://oin-hotosm-temp.s3.amazonaws.com/5f133...,Озеро Задорожное,"PROJCS[""WGS 84 / UTM zone 34N"",GEOGCS[""WGS 84""...","[23.911744, 49.547664, 23.924438, 49.557918]","POLYGON ((23.911744 49.547664, 23.924438 49.54...",0.059972,19559359,2020-07-11T06:15:00.000Z,2020-07-11T06:30:00.000Z,...,"{'bbox': [23.911744, 49.547664, 23.924438, 49....","{'_id': '5e46a3ebae704f00063a4869', 'name': 'V...","MULTIPOLYGON (((23.91234 49.55792, 23.91174 49...",5.997,1.0404,224,60,1,0,False
715,65d3b7fed1f3d200015493e0,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Cooperativa HUAYÑA PASTO 4,"\nPROJCRS[""WGS 84 / UTM zone 19S"",\n BASEGE...","[-66.954823, -18.047041, -66.938041, -18.032018]","POLYGON ((-66.954823 -18.047041, -66.938041 -1...",0.060000,127566170,2024-02-07T14:00:00.000Z,2024-02-07T15:00:00.000Z,...,"{'bbox': [-66.954823, -18.047041, -66.938041, ...","{'_id': '5d3f0ef9db56bc0007420e16', 'name': 'R...","MULTIPOLYGON (((-66.95482 -18.0322, -66.95465 ...",6.000,2.9536,0,1324,0,0,True
716,65d3a70ed1f3d200015493c9,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Cooperativa HUAYÑA PASTO 2,"\nPROJCRS[""WGS 84 / UTM zone 19S"",\n BASEGE...","[-66.954131, -18.034791, -66.937832, -18.02191]","POLYGON ((-66.954131 -18.034791, -66.937832 -1...",0.060000,119262238,2024-02-07T14:00:00.000Z,2024-02-07T15:00:00.000Z,...,"{'bbox': [-66.954131, -18.034791, -66.937832, ...","{'_id': '5d3f0ef9db56bc0007420e16', 'name': 'R...","MULTIPOLYGON (((-66.95413 -18.02208, -66.95398...",6.000,2.4598,0,1903,0,0,True

In [164]:
matched_gdf.to_file('../los_matches.gpkg')

In [ ]:

# Natural Earth
world_path = gpd.datasets.get_path("naturalearth_lowres")
world = gpd.read_file(world_path)

# Same CRS
matched_gdf = matched_gdf.to_crs(world.crs)

Keep country + continent + geometry
world_lookup = world[["ADMIN", "CONTINENT", "geometry"]].copy()

# Spatial intersection
matched_gdf = gpd.sjoin(
    matched_gdf,
    world_lookup,
    how="left",
    predicate="intersects"
)

# Rename columns
matched_gdf = matched_gdf.rename(columns={
    "ADMIN": "country",
    "CONTINENT": "continent"
})

# Remove join index
matched_gdf = matched_gdf.drop(columns=["index_right"], errors="ignore")
import pandas as pd
import geopandas as gpd

print(matched_gdf['continent'].isna().sum())
missing_mask = (
    matched_gdf["country"].isna() |
    matched_gdf["continent"].isna()
)

missing = matched_gdf.loc[missing_mask].copy()

print("Missing before:", len(missing))

# Project to meters for nearest-distance calculation
missing_projected = missing.to_crs("EPSG:6933")
world_projected = world_lookup.to_crs("EPSG:6933")

nearest = gpd.sjoin_nearest(
    missing_projected,
    world_projected[["ADMIN", "CONTINENT", "geometry"]],
    how="left",
    distance_col="match_distance"
)

# ONLY update missing values
for idx in missing.index:

    if pd.isna(matched_gdf.loc[idx, "country"]):
        matched_gdf.loc[idx, "country"] = nearest.loc[idx, "ADMIN"]

    if pd.isna(matched_gdf.loc[idx, "continent"]):
        matched_gdf.loc[idx, "continent"] = nearest.loc[idx, "CONTINENT"]


# Check result
print("Missing country:", matched_gdf["country"].isna().sum())
print("Missing continent:", matched_gdf["continent"].isna().sum())

In [185]:
non_zero = matched_gdf[matched_gdf['valid_los_matches'] != 0]
non_zero['country'].value_counts()

country
Bangladesh                     55
Russia                         48
Haiti                          29
Philippines                    27
Bolivia                        25
Japan                          24
Kenya                          22
Puerto Rico                    21
Mozambique                     17
Ukraine                        16
Montenegro                     13
Taiwan                         13
Sierra Leone                   12
Liberia                        12
Trinidad and Tobago             9
United States of America        8
Canada                          7
Brazil                          7
Georgia                         7
Colombia                        7
Paraguay                        6
Gabon                           5
Indonesia                       5
Argentina                       4
Iceland                         4
The Bahamas                     4
Ghana                           4
Ivory Coast                     3
Mexico                          3
United Kingdom                  3
India                           3
Fiji                            3
Malawi                          3
Moldova                         3
Belarus                         2
Thailand                        2
Uganda                          2
Latvia                          2
Norway                          2
Portugal                        1
United Republic of Tanzania     1
South Korea                     1
Senegal                         1
South Africa                    1
Turkey                          1
Vanuatu                         1
Nepal                           1
Hungary                         1
Chile                           1
Cameroon                        1
New Zealand                     1
Czechia                         1
Madagascar                      1
Nigeria                         1
Greece                          1
Name: count, dtype: int64

In [ ]:

# Match all_uav._id -> final_nonzero.scene_id
matched = all_uav.merge(
    final_nonzero,
    left_on='_id',
    right_on='scene_id',
    how='inner',
    suffixes=('_uav', '_los')
)

# Convert GeoJSON dict to Shapely geometry
matched['geometry'] = matched['geojson'].apply(shape)

# Create GeoDataFrame
matched_gdf = gpd.GeoDataFrame(
    matched,
    geometry='geometry',
    crs='EPSG:4326'
)

# Save as GeoPackage
out = '../cache_fast_bbox/oam/final_nonzero_uav2.gpkg'

matched_gdf.to_file(
    out,
    layer='uav_matches',
    driver='GPKG'
)

print(f"Saved {len(matched_gdf)} records to {out}")

In [186]:
# matched_gdf = gpd.read_file('../pre_dataset.gpkg')
matched_gdf.head()

,_id,uuid,title,projection,bbox,footprint,gsd,file_size,acquisition_start,acquisition_end,...,geometry,gsd_cm,area_km2,total_buildings,total_svi_points,buildings_on_path,valid_los_matches,has_overlap,country,continent
0,6a2d426391730de10f6bb33e,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,The Original City Center of Jeju City in Korea,"\nPROJCRS[""KGD2002 / Central Belt 2010"",\n ...","[126.516331, 33.506763, 126.533065, 33.518614]","POLYGON ((126.516331 33.506763, 126.533065 33....",0.010000,3231859293,2023-09-30T15:00:00.000Z,2023-10-31T14:59:00.000Z,...,"MULTIPOLYGON (((126.51633 33.51855, 126.5164 3...",1.000,2.0372,4908,471,2954,40,False,South Korea,Asia
1,652a6a10db601900014daad6,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,M2_22Feb22_35_transparent_mosaic_group1,"\nPROJCRS[""WGS 84 / UTM zone 46N"",\n BASEGE...","[90.360887, 23.837113, 90.3739, 23.846721]","POLYGON ((90.360887 23.837113, 90.3739 23.8371...",0.012120,1032502531,2023-10-13T18:00:00.000Z,2023-10-14T04:10:40.342Z,...,"MULTIPOLYGON (((90.36089 23.8465, 90.36108 23....",1.212,1.4090,1137,1877,889,30,False,Bangladesh,Asia
2,6529bc2ddb601900014daac4,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,sagufta_03Feb22_M1_transparent_mosaic_group1_33,"\nPROJCRS[""WGS 84 / UTM zone 46N"",\n BASEGE...","[90.374979, 23.829543, 90.384209, 23.842295]","POLYGON ((90.374979 23.829543, 90.384209 23.82...",0.012260,987138849,2023-10-12T18:00:00.000Z,2023-10-12T22:38:10.456Z,...,"MULTIPOLYGON (((90.38021 23.84053, 90.38021 23...",1.226,1.3265,1110,1665,558,11,False,Bangladesh,Asia
3,5a9f2f195a9ef7cb5da703e4,https://oin-hotosm-temp.s3.amazonaws.com/5a9f2...,TC-Gita-2018_UAV4R_Flight8,"GEOGCS[""WGS 84"",DATUM[""WGS_1984"",SPHEROID[""WGS...","[-175.2531898897765, -21.204050291607338, -175...","POLYGON ((-175.253189889777 -21.2040502916073,...",0.014327,891845475,2018-02-24T11:00:00.000Z,2018-02-24T11:00:00.000Z,...,"POLYGON ((-175.25319 -21.20405, -175.22681 -21...",1.433,29.7513,3979,66,351,18,True,Fiji,Oceania
4,5efb1ead8fec2a0005992d10,https://oin-hotosm-temp.s3.amazonaws.com/5efb1...,Ile de Saint Louis,"PROJCS[""WGS 84 / UTM zone 28N"",GEOGCS[""WGS 84""...","[-16.507769, 16.018057, -16.500973, 16.039249]","POLYGON ((-16.507769 16.018057, -16.500973 16....",0.014407,754731543,2019-08-17T22:00:00.000Z,2019-08-17T23:00:00.000Z,...,"MULTIPOLYGON (((-16.50777 16.0392, -16.50761 1...",1.441,1.7055,2511,1782,2055,59,False,Senegal,Africa

In [188]:
import geopandas as gpd
import pandas as pd
import networkx as nx
from pathlib import Path

# ─── CONFIGURATION ───
ISLAND_MATCH_CAP = 250  # Maximum matches we will keep from any single overlapping cluster

# # ─── 1. Load Data & Hardcode Missing Continents ───
# matched_gdf = gpd.read_file('../pre_dataset.gpkg')

if '_id' in matched_gdf.columns and 'scene_id' not in matched_gdf.columns:
    matched_gdf['scene_id'] = matched_gdf['_id'].astype(str)
else:
    matched_gdf['scene_id'] = matched_gdf['scene_id'].astype(str)

country_col = 'country' if 'country' in matched_gdf.columns else 'NAME_2'

matched_gdf['valid_los_matches'] = matched_gdf['valid_los_matches'].fillna(0).astype(int)

# ─── 2. Build Overlap Graph (Islands) ───
overlaps = gpd.sjoin(
    matched_gdf[['scene_id', 'geometry']], 
    matched_gdf[['scene_id', 'geometry']], 
    how='inner', predicate='intersects'
)

G = nx.Graph()
for sid in matched_gdf['scene_id']:
    G.add_node(sid)

for _, row in overlaps.iterrows():
    s1 = row['scene_id_left']
    s2 = row['scene_id_right']
    if s1 != s2:
        G.add_edge(s1, s2)

clusters = list(nx.connected_components(G))

# ─── 3. Aggregate Island Statistics & CAP MASSIVE CLUSTERS ───
islands = []
discarded_scenes = 0

for idx, cluster in enumerate(clusters):
    cluster_scenes = list(cluster)
    # Get all scenes in this cluster, sorted by highest match count first
    sub = matched_gdf[matched_gdf['scene_id'].isin(cluster_scenes)].sort_values(by='valid_los_matches', ascending=False)
    
    kept_scenes = []
    running_sum = 0
    
    for _, row in sub.iterrows():
        # If we already have enough matches from this overlapping cluster, discard the rest
        if running_sum >= ISLAND_MATCH_CAP and len(kept_scenes) > 0:
            discarded_scenes += 1
            continue
            
        kept_scenes.append(row['scene_id'])
        running_sum += row['valid_los_matches']
    
    # Filter 'sub' to only the scenes we decided to keep
    sub = sub[sub['scene_id'].isin(kept_scenes)]
    
    if running_sum > 0:
        islands.append({
            'island_id': idx,
            'scenes': kept_scenes,
            'scene_count': len(kept_scenes),
            'total_matches': int(sub['valid_los_matches'].sum()),
            'continents': list(sub['continent'].dropna().unique()),
            'countries': list(sub[country_col].dropna().unique()),
            'primary_continent': sub['continent'].mode().iloc[0] if not sub['continent'].empty else 'Unknown'
        })

df_islands = pd.DataFrame(islands)
print(f"Discarded {discarded_scenes} heavily overlapping scenes to enforce geographic diversity.")

# ─── 4. Continent-Stratified Bucket Allocation ───
buckets = {i: {'scenes': [], 'total_matches': 0, 'countries': set(), 'continents': set()} for i in range(1, 11)}

# Iterate through each continent one by one to ensure fair distribution
for continent in df_islands['primary_continent'].unique():
    # Sort the islands in this continent from largest to smallest
    cont_islands = df_islands[df_islands['primary_continent'] == continent].sort_values(by='total_matches', ascending=False)
    
    for _, island in cont_islands.iterrows():
        # Always give the next island to the bucket with the currently lowest total matches
        target_bucket = min(buckets.keys(), key=lambda b: buckets[b]['total_matches'])
        
        buckets[target_bucket]['scenes'].extend(island['scenes'])
        buckets[target_bucket]['total_matches'] += island['total_matches']
        buckets[target_bucket]['countries'].update(island['countries'])
        buckets[target_bucket]['continents'].update(island['continents'])

# ─── 5. Summary & Save Master Assignments ───
print("\n" + "=" * 80)
print("10 STUDENT BUCKET ALLOCATION SUMMARY (Stratified by Continent)")
print("=" * 80)

assignment_records = []
for b_id, b_data in sorted(buckets.items()):
    print(f"Bucket {b_id:02d}: Saved {len(b_data['scenes']):02d} scenes ({b_data['total_matches']} potential matches) -> student_{b_id:02d}_scenes.gpkg")
    print(f"           Continents: {', '.join(sorted(b_data['continents']))}")
    print(f"           Countries:  {', '.join(sorted(b_data['countries']))}")
    print("-" * 80)
    
    for sid in b_data['scenes']:
        assignment_records.append({'scene_id': sid, 'bucket_id': b_id})

df_assign = pd.DataFrame(assignment_records)
matched_gdf = matched_gdf.drop(columns=['bucket_id'], errors='ignore')
# Filter master matched_gdf to ONLY the scenes we assigned (drops the discarded overlaps)
matched_gdf = matched_gdf.merge(df_assign, on='scene_id', how='inner')

matched_gdf.to_file('../pre_dataset.gpkg', driver='GPKG')
matched_gdf.drop(columns=['geometry']).to_csv('../student_scene_assignments.csv', index=False)

# ─── 6. Export Individual Student GeoPackages ───
out_dir = Path('../student_packages')
out_dir.mkdir(parents=True, exist_ok=True)

for b_id in range(1, 11):
    student_gdf = matched_gdf[matched_gdf['bucket_id'] == b_id].copy()
    # columns_to_keep = ['scene_id', 'title', 'acquisition_start', 'gsd', 
    #                    'area_km2', 'total_buildings', 'total_svi_points', 'has_overlap',
    #                    'valid_los_matches', 'country', 'continent', 'geometry']
    
    # existing_columns = [c for c in columns_to_keep if c in student_gdf.columns]
    # student_gdf = student_gdf[existing_columns]
    
    out_file = out_dir / f'student_{b_id:02d}_scenes.gpkg'
    student_gdf.to_file(out_file, driver='GPKG')

Discarded 0 heavily overlapping scenes to enforce geographic diversity.

================================================================================
10 STUDENT BUCKET ALLOCATION SUMMARY (Stratified by Continent)
================================================================================
Bucket 01: Saved 18 scenes (911 potential matches) -> student_01_scenes.gpkg
           Continents: Africa, Asia, Europe, North America, South America
           Countries:  Argentina, Haiti, Iceland, India, Kenya, Liberia, Moldova, Montenegro, Mozambique, Portugal, Sierra Leone, Uganda, Ukraine
--------------------------------------------------------------------------------
Bucket 02: Saved 51 scenes (762 potential matches) -> student_02_scenes.gpkg
           Continents: Africa, Asia, Europe, North America, South America
           Countries:  Bangladesh, Belarus, Bolivia, Canada, Greece, Malawi, Mexico, Montenegro, Mozambique, Norway, Puerto Rico, Sierra Leone, Ukraine, United Kingdom, United Republic of Tanzania, United States of America
--------------------------------------------------------------------------------
Bucket 03: Saved 28 scenes (740 potential matches) -> student_03_scenes.gpkg
           Continents: Africa, Asia, Europe, North America
           Countries:  Bangladesh, Gabon, Haiti, Kenya, Liberia, Mozambique, Nigeria, Puerto Rico, Trinidad and Tobago, Ukraine
--------------------------------------------------------------------------------
Bucket 04: Saved 73 scenes (737 potential matches) -> student_04_scenes.gpkg
           Continents: Africa, Asia, Europe, North America, South America
           Countries:  Bolivia, Brazil, Canada, Chile, Colombia, Ivory Coast, Kenya, Mozambique, Paraguay, Philippines, Puerto Rico, Russia, Uganda, United States of America
--------------------------------------------------------------------------------
Bucket 05: Saved 58 scenes (761 potential matches) -> student_05_scenes.gpkg
           Continents: Africa, Asia, Europe, North America, Oceania, South America
           Countries:  Bangladesh, Colombia, Gabon, Georgia, Iceland, Japan, Kenya, Montenegro, Mozambique, New Zealand, Philippines, Russia, Sierra Leone, Thailand, Trinidad and Tobago, Ukraine, United States of America
--------------------------------------------------------------------------------
Bucket 06: Saved 42 scenes (737 potential matches) -> student_06_scenes.gpkg
           Continents: Africa, Asia, Europe, North America, South America
           Countries:  Bangladesh, Bolivia, Indonesia, Japan, Nepal, Paraguay, Philippines, Puerto Rico, South Africa, Taiwan, Trinidad and Tobago, Ukraine
--------------------------------------------------------------------------------
Bucket 07: Saved 42 scenes (737 potential matches) -> student_07_scenes.gpkg
           Continents: Africa, Asia, Europe, North America, South America
           Countries:  Argentina, Bangladesh, Bolivia, Colombia, Indonesia, Japan, Philippines, Puerto Rico, Russia, Sierra Leone, Taiwan, The Bahamas
--------------------------------------------------------------------------------
Bucket 08: Saved 62 scenes (737 potential matches) -> student_08_scenes.gpkg
           Continents: Africa, Asia, Europe, North America, Oceania, South America
           Countries:  Bangladesh, Bolivia, Brazil, Fiji, Georgia, Haiti, India, Ivory Coast, Japan, Madagascar, Malawi, Mexico, Montenegro, Mozambique, Paraguay, Philippines, Puerto Rico, Senegal, Trinidad and Tobago
--------------------------------------------------------------------------------
Bucket 09: Saved 60 scenes (736 potential matches) -> student_09_scenes.gpkg
           Continents: Africa, Asia, Europe, North America, Oceania, South America
           Countries:  Argentina, Bangladesh, Bolivia, Brazil, Cameroon, Colombia, Czechia, Fiji, Georgia, Ghana, Haiti, Hungary, Indonesia, Japan, Liberia, Moldova, Montenegro, Mozambique, Philippines, Puerto Rico, Russia, South Korea, Taiwan, Trinidad and Tobago, Turkey, Ukraine, United Kingdom, United States of America
--------------------------------------------------------------------------------
Bucket 10: Saved 56 scenes (736 potential matches) -> student_10_scenes.gpkg
           Continents: Africa, Asia, Europe, North America, Oceania, South America
           Countries:  Bangladesh, Belarus, Bolivia, Brazil, Colombia, Gabon, Georgia, Ghana, Haiti, Iceland, Indonesia, Japan, Latvia, Mexico, Paraguay, Philippines, Puerto Rico, Russia, Trinidad and Tobago, United Kingdom, United States of America, Vanuatu
--------------------------------------------------------------------------------

In [189]:
student_gdf

,_id,uuid,title,projection,bbox,footprint,gsd,file_size,acquisition_start,acquisition_end,...,area_km2,total_buildings,total_svi_points,buildings_on_path,valid_los_matches,has_overlap,country,continent,scene_id,bucket_id
10,60d204f1eade0f00079b58bf,https://oin-hotosm-temp.s3.amazonaws.com/60d20...,"Brgy. Pedro Vera Summit, Viga","PROJCS[""WGS 84 / UTM zone 51N"",GEOGCS[""WGS 84""...","[124.265884, 13.787232, 124.275683, 13.795791]","POLYGON ((124.265884 13.787232, 124.275683 13....",0.020000,224520893,2021-05-25T04:00:00.000Z,2021-05-26T03:59:00.000Z,...,1.0036,347,497,283,5,False,Philippines,Asia,60d204f1eade0f00079b58bf,10
20,6512962cceed5800019b01a7,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Baie Nettle post Irma hurricane,"\nPROJCRS[""WGS 84 / UTM zone 20N"",\n BASEGE...","[-63.117192, 18.057778, -63.106167, 18.066083]","POLYGON ((-63.117192 18.057778, -63.106167 18....",0.022780,213966879,2017-11-02T23:00:00.000Z,2017-11-03T00:00:00.000Z,...,1.0726,295,1,4,1,False,Puerto Rico,North America,6512962cceed5800019b01a7,10
23,6a5ebe846f2574e69520d8e3,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,MARIANO ROQUE ALONSO - LITORAL SUR,"\nPROJCRS[""WGS 84 / UTM zone 21S"",\n BASEGE...","[-57.577114, -25.235386, -57.555704, -25.210137]","POLYGON ((-57.577114 -25.235386, -57.555704 -2...",0.023410,932289971,2026-01-15T03:00:00.000Z,2026-01-30T04:00:00.000Z,...,6.0255,4906,270,1966,18,False,Paraguay,South America,6a5ebe846f2574e69520d8e3,10
34,5d9977910ca8d70007c491d9,https://oin-hotosm-temp.s3.amazonaws.com/5d997...,Kallucata,"PROJCS[""WGS 84 / UTM zone 19S"",GEOGCS[""WGS 84""...","[-68.306035, -16.522368, -68.29568, -16.510509]","POLYGON ((-68.306035 -16.522368, -68.29568 -16...",0.025000,418366020,2018-11-24T14:00:00.000Z,2018-11-24T15:00:00.000Z,...,1.4506,12,1358,12,2,False,Bolivia,South America,5d9977910ca8d70007c491d9,10
42,59e62b963d6412ef7220a3fd,https://oin-hotosm-temp.s3.amazonaws.com/59639...,"Barangay Wilson, Mayorga, Leyte","PROJCS[""WGS 84 / UTM zone 51N"",GEOGCS[""WGS 84""...","[124.95670756098147, 10.843446771755657, 124.9...","POLYGON ((124.956707560981 10.8434467717557,12...",0.027130,661951246,2017-05-10T19:04:00.000Z,2017-05-16T16:25:00.000Z,...,3.9473,461,1343,299,12,True,Philippines,Asia,59e62b963d6412ef7220a3fd,10
44,617ea3af8ebcb9000515c52a,https://oin-hotosm-temp.s3.amazonaws.com/617e8...,chofu20211031disasterdrill0907mapconcierge00DSM,"PROJCS[""WGS 84 / UTM zone 54N"",GEOGCS[""WGS 84""...","[139.542207, 35.633591, 139.563791, 35.643102]","POLYGON ((139.542207 35.633591, 139.563791 35....",0.027470,4319280166,2021-10-31T00:00:00.000Z,2021-10-31T01:00:00.000Z,...,2.0556,2862,285,120,0,False,Japan,Asia,617ea3af8ebcb9000515c52a,10
45,617e93268ebcb9000515c509,https://oin-hotosm-temp.s3.amazonaws.com/617e9...,chofu20211031disasterdrill0907mapconcierge00,"PROJCS[""WGS 84 / UTM zone 54N"",GEOGCS[""WGS 84""...","[139.542207, 35.633591, 139.563791, 35.643102]","POLYGON ((139.542207 35.633591, 139.563791 35....",0.027470,275951166,2021-10-31T00:00:00.000Z,2021-10-31T01:00:00.000Z,...,2.0556,3055,162,56,0,False,Japan,Asia,617e93268ebcb9000515c509,10
58,5a95bd405a9ef7cb5d8e1a40,https://oin-hotosm-temp.s3.amazonaws.com/5a95b...,Laplaine - North section - Dominica,"PROJCS[""WGS 84 / UTM zone 20N"",GEOGCS[""WGS 84""...","[-61.254509417583115, 15.332117276173879, -61....","POLYGON ((-61.2545094175831 15.3321172761739,-...",0.029320,130210488,2018-02-16T08:00:00.000Z,2018-02-16T09:00:00.000Z,...,1.1900,138,270,28,1,True,Puerto Rico,North America,5a95bd405a9ef7cb5d8e1a40,10
59,617f0bde8ebcb9000515c52e,https://oin-hotosm-temp.s3.amazonaws.com/617f0...,chofu20211031,"PROJCS[""WGS 84 / UTM zone 54N"",GEOGCS[""WGS 84""...","[139.541335, 35.631844, 139.565628, 35.644555]","POLYGON ((139.541335 35.631844, 139.565628 35....",0.029497,258817971,2021-10-30T21:00:00.000Z,2021-10-31T00:00:00.000Z,...,3.0920,5860,144,43,1,False,Japan,Asia,617f0bde8ebcb9000515c52e,10
74,6633bbde6049ef00013b8250,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Búðadalur,"\nPROJCRS[""ISN2016 / Lambert 2016"",\n BASEG...","[-21.777573, 65.100439, -21.751336, 65.117697]","POLYGON ((-21.777573 65.100439, -21.751336 65....",0.030054,629091343,2022-06-01T14:40:00.000Z,2022-06-01T15:50:00.000Z,...,2.3481,184,1678,98,3,False,Iceland,Europe,6633bbde6049ef00013b8250,10
83,59e62b973d6412ef7220a410,https://oin-hotosm-temp.s3.amazonaws.com/59666...,"Barangay Union, Mayorga, Leyte","PROJCS[""WGS 84 / UTM zone 51N"",GEOGCS[""WGS 84""...","[124.97691867713598, 10.845445563468175, 125.0...","POLYGON ((124.976918677136 10.8454455634682,12...",0.030850,1109360237,2017-05-04T12:56:00.000Z,2017-05-17T16:10:00.000Z,...,7.4238,1491,570,456,19,True,Philippines,Asia,59e62b973d6412ef7220a410,10
84,63ccad73e886ab000766f716,https://oin-hotosm-temp.s3.amazonaws.com/63cca...,Mallard's Landing,"PROJCS[""WGS 84 / UTM zone 17N"",GEOGCS[""WGS 84""...","[-83.610721, 34.099708, -83.599953, 34.112655]","POLYGON ((-83.610721 34.099708, -83.599953 34....",0.031000,241888736,2023-01-21T16:23:00.000Z,2023-01-21T17:42:00.000Z,...,1.4223,277,1846,271,49,False,United States of America,North America,63ccad73e886ab000766f716,10
105,615cde11c47ebe0007c75941,https://oin-hotosm-temp.s3.amazonaws.com/615cd...,Haiti-Aquin - October 2021,"PROJCS[""WGS 84 / UTM zone 18N"",GEOGCS[""WGS 84""...","[-73.402721, 18.272808, -73.383438, 18.290759]","POLYGON ((-73.402721 18.272808, -73.383438 18....",0.034400,519472831,2021-10-01T05:00:00.000Z,2021-10-01T06:00:00.000Z,...,4.0496,3292,83,1171,8,False,Haiti,North America,615cde11c47ebe0007c75941,10
124,6a3ccb92a4e3edb1f71fddce,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Chattogram UAV 46,"\nPROJCRS[""WGS 84 / UTM zone 46N"",\n BASEGE...","[91.774214, 22.251111, 91.799108, 22.262135]","POLYGON ((91.774214 22.251111, 91.799108 22.25...",0.035000,737362138,2026-06-23T18:00:00.000Z,2026-06-24T12:13:31.236Z,...,3.1294,3442,103,11,2,False,Bangladesh,Asia,6a3ccb92a4e3edb1f71fddce,10
143,64a6d09064adbc00012e09a1,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Mazsalaca,"\nPROJCRS[""WGS 84 / UTM zone 35N"",\n BASEGE...","[25.036946, 57.85162, 25.054438, 57.861618]","POLYGON ((25.036946 57.85162, 25.054438 57.851...",0.035487,125511042,2022-06-24T21:00:00.000Z,2022-06-25T20:59:00.000Z,...,1.1464,164,968,120,3,True,Latvia,Europe,64a6d09064adbc00012e09a1,10
144,59e62b7a3d6412ef72209530,https://oin-hotosm-temp.s3.amazonaws.com/56fa5...,Erromango - Ipota,"PROJCS[""WGS 84 / UTM zone 59S"",GEOGCS[""WGS 84""...","[169.27958832126677, -18.861399456033183, 169....","POLYGON((169.27967792955903 -18.8525201850488,...",0.035600,74477385,2015-04-04T00:00:00.000Z,2015-04-04T23:30:00.000Z,...,1.0337,242,120,5,1,False,Vanuatu,Oceania,59e62b7a3d6412ef72209530,10
171,64975cdba2f35c00061c1095,https://oin-hotosm-temp.s3.amazonaws.com/64975...,Mazsalaca 2,"\nPROJCRS[""WGS 84 / UTM zone 35N"",\n BASEGE...","[25.040119, 57.859927, 25.054724, 57.870752]","POLYGON ((25.040119 57.859927, 25.054724 57.85...",0.037571,107000512,2022-06-24T17:30:00.000Z,2022-06-24T18:00:00.000Z,...,1.0361,313,739,199,5,True,Latvia,Europe,64975cdba2f35c00061c1095,10
174,61f2a715bc4fd60005518147,https://oin-hotosm-temp.s3.amazonaws.com/61f29...,katori20220127sawara1327mapconcierge00arw00,"PROJCS[""WGS 84 / UTM zone 54N"",GEOGCS[""WGS 84""...","[140.496911, 35.892653, 140.517249, 35.910661]","POLYGON ((140.496911 35.892653, 140.517249 35....",0.037710,173952251,2022-01-27T04:27:00.000Z,2022-01-27T05:10:00.000Z,...,3.6553,966,1926,907,10,False,Japan,Asia,61f2a715bc4fd60005518147,10
188,6145f9288ab3f40005221e34,https://oin-hotosm-temp.s3.amazonaws.com/6145f...,SANTIAGO DE HUATA,"PROJCS[""WGS 84 / UTM zone 19S"",GEOGCS[""WGS 84""...","[-68.820334, -16.058912, -68.808682, -16.049527]","POLYGON ((-68.820334 -16.058912, -68.808682 -1...",0.040000,88901582,2018-05-05T14:00:00.000Z,2018-05-05T15:00:00.000Z,...,1.2948,2,732,2,1,False,Bolivia,South America,6145f9288ab3f40005221e34,10
195,6a3839fb76654b2b3d24eda6,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,"Corregimiento Guarumo, Cáceres","\nGEOGCRS[""WGS 84"",\n ENSEMBLE[""World Geode...","[-75.215819, 7.847923, -75.203293, 7.859243]","POLYGON ((-75.215819 7.847923, -75.203293 7.84...",0.041133,165069401,2026-05-28T05:00:00.000Z,2026-05-29T01:30:11.084Z,...,1.7307,940,657,298,14,False,Colombia,South America,6a3839fb76654b2b3d24eda6,10
204,63a3be4915be67000614e393,https://oin-hotosm-temp.s3.amazonaws.com/63a3b...,Cateura_2021,"PROJCS[""WGS 84 / UTM zone 21S"",GEOGCS[""WGS 84""...","[-57.6487, -25.331232, -57.63748, -25.321876]","POLYGON ((-57.6487 -25.331232, -57.63748 -25.3...",0.042720,129820288,2021-12-29T03:00:00.000Z,2021-12-30T02:30:00.000Z,...,1.1691,2344,496,608,28,True,Paraguay,South America,63a3be4915be67000614e393,10
210,63a4e090eb16e8000519a1b1,https://oin-hotosm-temp.s3.amazonaws.com/63a4d...,Cateura_2021,"PROJCS[""WGS 84 / UTM zone 21S"",GEOGCS[""WGS 84""...","[-57.647142, -25.334067, -57.635519, -25.325608]","POLYGON ((-57.647142 -25.334067, -57.635519 -2...",0.043870,105320372,2021-12-29T03:00:00.000Z,2021-12-30T02:30:00.000Z,...,1.0949,1234,276,557,32,True,Paraguay,South America,63a4e090eb16e8000519a1b1,10
233,59e62b943d6412ef7220a29d,https://oin-hotosm-temp.s3.amazonaws.com/593eb...,Praia_Melao_STP,"PROJCS[""WGS 84 / UTM zone 32N"",GEOGCS[""WGS 84""...","[6.744310302440271, 0.300445422773979, 6.75207...","POLYGON ((6.74431030244027 0.30044542277398,6....",0.045290,79563776,2017-02-28T14:00:00.000Z,2017-03-03T15:00:00.000Z,...,1.2907,98,580,28,2,False,Gabon,Africa,59e62b943d6412ef7220a29d,10
238,69bc113d0b84272663f73f5d,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Matthew 2016 - Roseaux DSM,"\nPROJCRS[""WGS 84 / UTM zone 18N"",\n BASEGE...","[-74.028748, 18.596858, -74.008665, 18.6025]","POLYGON ((-74.028748 18.596858, -74.008665 18....",0.045970,1382443536,2016-11-01T23:00:00.000Z,2016-11-02T00:00:00.000Z,...,1.3232,466,57,177,17,True,Haiti,North America,69bc113d0b84272663f73f5d,10
239,69bc10aa0b84272663f73dc2,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Matthew 2016 - Roseaux,"\nPROJCRS[""WGS 84 / UTM zone 18N"",\n BASEGE...","[-74.028739, 18.596861, -74.008669, 18.602498]","POLYGON ((-74.028739 18.596861, -74.008669 18....",0.045970,143098553,2016-11-01T23:00:00.000Z,2016-11-02T00:00:00.000Z,...,1.3211,466,57,177,17,True,Haiti,North America,69bc10aa0b84272663f73dc2,10
257,67c1b10faaf1e28d21d24471,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,DroneTM-Grand_Bay_DOM-01,"\nPROJCRS[""WGS 84 / UTM zone 20N"",\n BASEGE...","[-61.326807, 15.236825, -61.313328, 15.248403]","POLYGON ((-61.326807 15.236825, -61.313328 15....",0.048107,149915978,2025-01-26T16:00:00.000Z,2025-01-26T17:00:00.000Z,...,1.8552,1481,1924,1039,21,False,Trinidad and Tobago,North America,67c1b10faaf1e28d21d24471,10
261,5f87c60b8d05870005b91bbf,https://oin-hotosm-temp.s3.amazonaws.com/5f87c...,hakone20170307ashinoko01ebee01,"PROJCS[""WGS 84 / UTM zone 54N"",GEOGCS[""WGS 84""...","[139.010272, 35.184826, 139.031072, 35.196613]","POLYGON ((139.010272 35.184826, 139.031072 35....",0.048507,67291741,2017-03-06T15:00:00.000Z,2017-03-06T16:00:00.000Z,...,2.4687,586,218,201,5,False,Japan,Asia,5f87c60b8d05870005b91bbf,10
267,5a95eb5e5a9ef7cb5d8ea156,https://oin-hotosm-temp.s3.amazonaws.com/5a95e...,Laplaine 2 - Dominica,"PROJCS[""WGS 84 / UTM zone 20N"",GEOGCS[""WGS 84""...","[-61.255806344980414, 15.322486218426224, -61....","POLYGON ((-61.2558063449804 15.3224862184262,-...",0.049340,102425457,2018-02-20T08:00:00.000Z,2018-02-20T09:00:00.000Z,...,1.5350,545,136,48,0,True,Puerto Rico,North America,5a95eb5e5a9ef7cb5d8ea156,10
277,6937df706f4bcbf66de30602,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Trevone Strip,"\nPROJCRS[""WGS 84 / UTM zone 30N"",\n BASEGE...","[-4.982825, 50.536466, -4.969152, 50.549493]","POLYGON ((-4.982825 50.536466, -4.969152 50.53...",0.049997,20820807,2024-10-13T23:00:00.000Z,2024-10-14T11:50:10.949Z,...,1.3947,494,45,10,1,False,United Kingdom,Europe,6937df706f4bcbf66de30602,10
278,66e405d9cd0baa0001b6212b,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Oldfadama Agbogloshie_combined_high_compression,"\nPROJCRS[""WGS 84 / UTM zone 30N"",\n BASEGE...","[-0.225852, 5.541892, -0.214147, 5.55653]","POLYGON ((-0.225852 5.541892, -0.214147 5.5418...",0.049998,151795690,2024-08-26T18:30:00.000Z,2024-08-29T19:30:00.000Z,...,2.1012,23143,693,8156,77,True,Ghana,Africa,66e405d9cd0baa0001b6212b,10
279,66e3c6e7cd0baa0001b62114,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Oldfadama Agbogloshie_combined_uncompressed,"\nPROJCRS[""WGS 84 / UTM zone 30N"",\n BASEGE...","[-0.225852, 5.541892, -0.214147, 5.55653]","POLYGON ((-0.225852 5.541892, -0.214147 5.5418...",0.049998,3051682559,2024-08-27T18:30:00.000Z,2024-08-29T19:30:00.000Z,...,2.1012,23143,693,7851,77,True,Ghana,Africa,66e3c6e7cd0baa0001b62114,10
282,6682707e1b35ab0001a53794,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Gonio North - Batumi (GE),"\nPROJCRS[""WGS 84 / UTM zone 37N"",\n BASEGE...","[41.564725, 41.560589, 41.576035, 41.570356]","POLYGON ((41.564725 41.560589, 41.576035 41.56...",0.049999,46726157,2024-06-30T17:08:02.000Z,2024-06-30T18:08:02.000Z,...,1.0183,417,1733,319,4,False,Georgia,Asia,6682707e1b35ab0001a53794,10
297,5d0755634d360d0006ca1792,https://oin-hotosm-temp.s3.amazonaws.com/5d075...,"Tulamben, Kubu, Karangasem","PROJCS[""WGS 84 / UTM zone 50S"",GEOGCS[""WGS 84""...","[115.606099, -8.305209, 115.615694, -8.296413]","POLYGON ((115.606099 -8.305209, 115.615694 -8....",0.050000,43347346,2017-10-02T17:15:06.000Z,2017-10-02T18:15:06.000Z,...,1.0290,240,179,94,16,False,Indonesia,Asia,5d0755634d360d0006ca1792,10
329,63d20e4ea72c5f0006688560,https://oin-hotosm-temp.s3.amazonaws.com/63d20...,F_53,"PROJCS[""WGS 84 / UTM zone 46N"",GEOGCS[""WGS 84""...","[90.440627, 23.678728, 90.450601, 23.687914]","POLYGON ((90.440627 23.678728, 90.450601 23.67...",0.050000,119890193,2023-01-24T18:00:00.000Z,2023-01-25T10:48:51.756Z,...,1.0338,2779,266,693,47,False,Bangladesh,Asia,63d20e4ea72c5f0006688560,10
339,6a8aea77d6e62aed388be059,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Mariana - Heritage perimeter (5cm GSD),"\nPROJCRS[""SIRGAS 2000 / UTM zone 23S"",\n B...","[-43.425485, -20.387256999999998, -43.408249, ...","POLYGON ((-43.425485 -20.387257, -43.408249 -2...",0.050000,266131405,2026-08-21T10:30:00.000Z,2026-08-21T12:30:00.000Z,...,3.6703,439,1871,431,13,False,Brazil,South America,6a8aea77d6e62aed388be059,10
354,5ed2514057676e00057f5845,https://oin-hotosm-temp.s3.amazonaws.com/5ed24...,Old Fadama - Agbogbloshie,"PROJCS[""WGS 84 / UTM zone 30N"",GEOGCS[""WGS 84""...","[-0.23305599999999999, 5.53608, -0.21681699999...","POLYGON ((-0.233056 5.53608, -0.216817 5.53608...",0.050082,210798129,2020-05-26T00:00:00.000Z,2020-05-27T01:00:00.000Z,...,4.7544,25118,1955,19951,98,True,Ghana,Africa,5ed2514057676e00057f5845,10
364,5d25d86c161a790005c03e70,https://oin-hotosm-temp.s3.amazonaws.com/5d25d...,Lupang Arenda Ortho Image 246,"PROJCS[""WGS 84 / UTM zone 51N"",GEOGCS[""WGS 84""...","[121.107744, 14.530301, 121.115502, 14.541871]","POLYGON ((121.107744 14.530301, 121.115502 14....",0.051600,70336354,2019-07-07T02:00:00.000Z,2019-07-07T04:00:00.000Z,...,1.0705,7474,91,1835,41,False,Philippines,Asia,5d25d86c161a790005c03e70,10
387,5e570b312408ff000614bb86,https://oin-hotosm-temp.s3.amazonaws.com/5e570...,"SPb, Obvodny, Mitrof-Moskovsy, 1","PROJCS[""WGS 84 / UTM zone 36N"",GEOGCS[""WGS 84""...","[30.296387, 59.900603, 30.32214, 59.9104559999...","POLYGON ((30.296387 59.900603, 30.32214 59.900...",0.053340,92759737,2020-02-25T12:37:00.000Z,2020-02-25T12:57:00.000Z,...,1.5677,491,1882,259,9,True,Russia,Europe,5e570b312408ff000614bb86,10
392,5ca3fde5e5635f000690af72,https://oin-hotosm-temp.s3.amazonaws.com/5ca3f...,"SPb, Rizhsky pr, Stepana Razina - Staropetergo...","PROJCS[""WGS 84 / UTM zone 36N"",GEOGCS[""WGS 84""...","[30.260108, 59.907323, 30.286455, 59.917761]","POLYGON ((30.260108 59.907323, 30.286455 59.90...",0.053501,69976501,2019-04-02T08:39:00.000Z,2019-04-02T09:00:00.000Z,...,1.6987,598,218,160,5,True,Russia,Europe,5ca3fde5e5635f000690af72,10
398,5f46e7c7f4b82d0005a702a3,https://oin-hotosm-temp.s3.amazonaws.com/5f46e...,"СПб, Лиговский проспект, Обводный - Курская, D...","PROJCS[""WGS 84 / UTM zone 36N"",GEOGCS[""WGS 84""...","[30.335514, 59.90621, 30.366715, 59.919858]","POLYGON ((30.335514 59.90621, 30.366715 59.906...",0.053804,111612715,2020-03-03T11:25:00.000Z,2020-03-03T11:40:00.000Z,...,2.6302,1153,52,16,2,False,Russia,Europe,5f46e7c7f4b82d0005a702a3,10
399,5bd71cb340de3f0005f21522,https://oin-hotosm-temp.s3.amazonaws.com/5bd71...,"SPb, Old Petergof, SPBGU, Timyashkino","PROJCS[""WGS 84 / UTM zone 35N"",GEOGCS[""WGS 84""...","[29.811425, 59.867175, 29.848463, 59.879798]","POLYGON ((29.811425 59.867175, 29.848463 59.86...",0.053862,150216531,2018-10-26T09:48:00.000Z,2018-10-26T10:05:00.000Z,...,2.8912,1393,236,338,0,True,Russia,Europe,5bd71cb340de3f0005f21522,10
401,5e570b5b2408ff000614bb88,https://oin-hotosm-temp.s3.amazonaws.com/5e570...,"SPb, Obvodny, Mitrof-Moskovsy, 3","PROJCS[""WGS 84 / UTM zone 36N"",GEOGCS[""WGS 84""...","[30.2967, 59.89042, 30.322739, 59.899707]","POLYGON ((30.2967 59.89042, 30.322739 59.89042...",0.053895,94352181,2020-02-25T13:45:00.000Z,2020-02-25T14:04:00.000Z,...,1.4945,355,3,0,0,True,Russia,Europe,5e570b5b2408ff000614bb88,10
413,5e570b382408ff000614bb87,https://oin-hotosm-temp.s3.amazonaws.com/5e570...,"SPb, Obvodny, Mitrof-Moskovsy, 2","PROJCS[""WGS 84 / UTM zone 36N"",GEOGCS[""WGS 84""...","[30.295967, 59.896094, 30.322236, 59.904853]","POLYGON ((30.295967 59.896094, 30.322236 59.89...",0.054082,88235541,2020-02-25T13:12:00.000Z,2020-02-25T13:31:00.000Z,...,1.4217,407,33,1,0,True,Russia,Europe,5e570b382408ff000614bb87,10
416,5d8f556372f3f60007854eaf,https://oin-hotosm-temp.s3.amazonaws.com/5d8f5...,SPb. New building on Pulkovskoye shosse,"PROJCS[""WGS 84 / UTM zone 36N"",GEOGCS[""WGS 84""...","[30.316707, 59.815452, 30.347401, 59.823662]","POLYGON ((30.316707 59.815452, 30.347401 59.81...",0.054222,85777980,2019-09-25T12:23:00.000Z,2019-09-25T12:42:00.000Z,...,1.5609,111,1744,67,5,False,Russia,Europe,5d8f556372f3f60007854eaf,10
420,64b5934ef1006f000147af8a,https://oin-hotosm-temp.s3.us-east-1.amazonaws...,Centro Ecoturístico Patzingo y zonas aledañas ...,"\nPROJCRS[""WGS 84 / UTM zone 13N"",\n BASEGE...","[-102.202081, 19.485894, -102.192278, 19.496574]","POLYGON ((-102.202081 19.485894, -102.192278 1...",0.054391,75237766,2023-07-13T16:47:00.000Z,2023-07-13T17:03:00.000Z,...,1.2160,23,296,8,1,False,Mexico,North America,64b5934ef1006f000147af8a,10
433,5cba34f8761d2e00050690d5,https://oin-hotosm-temp.s3.amazonaws.com/5cba3...,"SPb, Petergof, Baush lake","PROJCS[""WGS 84 / UTM zone 35N"",GEOGCS[""WGS 84""...","[29.843774, 59.879931, 29.865526, 59.894286]","POLYGON ((29.843774 59.879931, 29.865526 59.87...",0.055370,106586755,2019-04-16T15:49:00.000Z,2019-04-16T16:11:00.000Z,...,1.9302,1404,159,137,1,True,Russia,Europe,5cba34f8761d2e00050690d5,10
441,5bc324c4408eba0008a5dd75,https://oin-hotosm-temp.s3.amazonaws.com/5bc32...,"SPb, Rizhsky pr","PROJCS[""WGS 84 / UTM zone 36N"",GEOGCS[""WGS 84""...","[30.270688, 59.906458, 30.300735, 59.918329]","POLYGON ((30.270688 59.906458, 30.300735 59.90...",0.055874,118632094,2018-10-11T12:38:00.000Z,2018-10-11T12:57:00.000Z,...,2.2032,922,74,51,2,True,Russia,Europe,5bc324c4408eba0008a5dd75,10
443,5eaddc5b3295f300072a6d8b,https://oin-hotosm-temp.s3.amazonaws.com/5eadd...,Старый Петергоф,"PROJCS[""WGS 84 / UTM zone 35N"",GEOGCS[""WGS 84""...","[29.851177, 59.877747, 29.876109, 59.890735]","POLYGON ((29.851177 59.877747, 29.876109 59.87...",0.056219,95174363,2020-05-01T15:24:00.000Z,2020-05-01T15:41:00.000Z,...,2.0019,882,550,315,14,True,Russia,Europe,5eaddc5b3295f300072a6d8b,10